[build-system]
requires = ["setuptools>=61.2"]
build-backend = "setuptools.build_meta"

[project]
readme = "README.md"
name = "ev3robot"
version = "0.1.0"
description = "EV3 robot program" 

dependencies = ['ev3dev2simulator==2.0.10']
