#!/usr/bin/env bash

script_dir=$(dirname $0)
source "$script_dir/config.bash"

docker run --detach \
    --rm \
    --hostname="$CONFIG_CONTAINER" \
    --publish="127.0.0.1:$CONFIG_HOSTPORT_RDP:3389/tcp" \
    --publish="127.0.0.1:$CONFIG_HOSTPORT_EV3DEV2:6840/tcp" \
    --publish="127.0.0.1:$CONFIG_HOSTPORT_BLUETOOTH:6841/tcp" \
    --name="$CONFIG_CONTAINER" \
    "$CONFIG_IMAGE"
