#!/usr/bin/env bash

script_dir=$(dirname $0)
projectdir=$( cd "$script_dir/.." && pwd  )
source "$script_dir/config.bash"

docker run --detach \
    --rm \
    --hostname="$CONFIG_CONTAINER" \
    --publish="127.0.0.1:$CONFIG_HOSTPORT_RDP:3389/tcp" \
    --publish="127.0.0.1:$CONFIG_HOSTPORT_EV3DEV2:6840/tcp" \
    --publish="127.0.0.1:$CONFIG_HOSTPORT_BLUETOOTH:6841/tcp" \
    --name="$CONFIG_CONTAINER" \
    --mount type=bind,source="$projectdir",target="/home/$CONFIG_USER/pyproject/src" \
    "$CONFIG_IMAGE"

# --mount type=bind,source="$projectdir",target="/workspace" \
